Add maxlength indicator to Add Movie inputs
zorchenhimer/MoviePolls pull request #133
Opened 2022-10-04 22:00 UTC by wyrid

Adds maxlength indicator to form input fields in the Add Movies page that tracks current / maxlength of specific input fields.

This also adds a maxlength indicator to the Reference Links textarea that tracks the current / maxlength of each individual link in the textarea, separated by a newline.

Currently only used in add-movies, but can be added where needed.

This should close #103.

2022-10-04 22:07 UTC, CptPie reviewed
Thank you for your contribution - on a quick look it looks fine, i'll test it locally before approving

2022-10-16 20:34 UTC, CptPie requested changes
Visually it looks great, just fix my two remarks and we'll merge it in.

Thanks again for your contribution.

2022-10-16 20:34 UTC, CptPie commented on web/templates/add-movie.html
> +                    <textarea name="Links" id="Links">{{if (index .Fields "Links")}}{{if (index .Fields "Links").Value}}{{ (index .Fields "Links").Value}}{{end}}{{end}}</textarea>
maxlength parameter missing here

2022-10-16 20:34 UTC, CptPie commented on web/templates/add-movie.html
> +                <textarea name="Links" id="Links">{{if (index .Fields "Links")}}{{if (index .Fields "Links").Value}}{{(index .Fields "Links").Value}}{{end}}{{end}}</textarea>
maxlength also missing here

2022-10-16 20:36 UTC, CptPie commented
![image](https://user-images.githubusercontent.com/23438606/196057080-74adcb11-4088-4a7f-97aa-9882f56e7f38.png)
adding a picture for zorch :P

2022-10-17 21:28 UTC, wyrid commented
I did not add maxlength to the links fields since they are 500 characters per link, not 500 characters total. Adding maxlength will restrict the field to 500 characters total, as seen in this image:
![Screenshot from 2022-10-17 17-21-49](https://user-images.githubusercontent.com/6940264/196286894-16860e65-015f-4e0d-9e4c-facd57dbd254.png)

What I opted to do was to not restrict the total length of the field, but show a visual indication of when it is over the length.
![Screenshot from 2022-10-17 17-23-43](https://user-images.githubusercontent.com/6940264/196286979-73dca150-4c16-44cf-ba14-d6316c2fc4a4.png)

If the user still submits even though it is over, it returns the error server side.
![Screenshot from 2022-10-17 17-23-56](https://user-images.githubusercontent.com/6940264/196286988-7fe07da0-f160-4d7b-9234-9371f8feb705.png)

But if each link is under 500, it'll submit successfully.
![Screenshot from 2022-10-17 17-24-29](https://user-images.githubusercontent.com/6940264/196287008-84eff8e2-720f-41ac-a301-2dc57ecc0892.png)

2022-10-17 22:57 UTC, CptPie commented
Fair enough, i completely forgot about this (even though i am pretty sure i wrote that part of the logic myself lmao).
Closed and merged - ty again :)

2022-10-17 22:57 UTC, merged